- .travis.yml
- ansible/install.yml
- mininet/node.py
- mininet/test/test_containernet.py
- setup.py
-use latest docker python api version 2.0.2
this requires only a single change using the docker.APIClient (instead of docker.Client)
-bind by default the ports of the VNFs (ports exposed by EXPOSE statement in dockerfile) to a free port on the host. docker will choose an available port on the host.
-the binded portnumber can be specified also, by providing a dict to the Docker host init.
See usage documentation in docker py: https://docker-py.readthedocs.io/en/stable/api.html#module-docker.api.container
unit tests and ansible install scripts were tested on normal ubuntu 14.04 installation.
> Docker API updates

- mininet/cli.py
- mininet/node.py
- mininet/term.py
Changes:
1. Use docker.from_env().api instead of Hardcoding APIClient endpoint (https://github.com/containernet/containernet/issues/35)
2. Shift Container creation code to __init__:
This was done to make sure to clarify the purpose of startShell().
It is only meant to run the working shell for our commands. For
the container to keep running, it must halt at a dummy shell when
executing docker run from docker-py API.
3. Allow regenerating shell if necessary
4. Fixed: popen, pexec
5. Other minor bug fixes and typos
6. Fixed: SIGINT causes CLI to when running Docker Host commands (https://github.com/containernet/containernet/issues/33)
7. Added/Fixed: Maketerms (xterm/gterm) support for Docker Hosts
> Refactor fixes and optimizations

- mininet/node.py
Add DNS as optional parameter for container creation.
Following DockerPy API, this parameter is an array of strings specifying the IPs for DNS resolvers to be set inside the container.
> Add DNS as optional parameter

- util/install.sh
Makes the installation more robust aginst firewalls etc.
Closes #48 
> Fix: Use https:// for git clones in install.sh

- examples/docker_cpuset.py
- mininet/node.py
> Fix: Wrong parameter name in docker_cpuset example.

- examples/dockerhosts.py
- mininet/node.py
network. Ports need to be exposed AND mapped.
> Fix: Allow port forwarding via docker's management

- Dockerfile.centos
- ansible/install_centos.yml
- util/docker/Dockerfile.centos7
- util/docker/entrypoint_centos.sh
- util/install.sh
The install script for Containernet has been updated to support CentOS along RHEL and Fedora. A new Ansible script has been provided, which is specific for CentOS deployment, in addition to the Ubuntu deployment script.
> Support for CentOS

- .travis.yml
- ansible/install_centos.yml
- util/docker/Dockerfile.centos7
This PR includes fixes in Ansible script and Dockerfile for CentOS deployment, as raised by the bug #70 . 
The issue happens because the Ansible version which is installed  by Dockerfile is older than the version available in the EPEL repository, and it is upgraded to the latest release by the Ansible playbook. The two versions are not compatible (e.g. class objects are different), hence the bug occurs when running the playbook.
The fix consists of enabling EPEL repository and upgrading all the packages in the Dockerfile itself, before running any package upgrade and install in the Ansible playbook.
> Fixed Ansible error in CentOS-based Docker deployment

- mininet/node.py
Hi,
This is a very minor requested feature, 
but I think it would be good if containernet automatically finds existing dockers which have the same name requested from AddDocker(), and remove them before creating.
I know containernet already terminates all made dockers when a user types "exit" or "Ctrl+D".
But I've got some annoying situations, for example, I needed to manually remove the container when I attached the docker session using the command "docker attach" and exit from it.
The reason was that I think containernet is not able to clean stopped containers when exiting it.
So, it turns out that there remains previously created docker containers, and this caused errors when I make a containernet again, since the stopped container has a same name.
Therefore, like the --rm option in …
> Add --rm option feature to AddDocker

- examples/containernet_example_cmd_field.py
- mininet/node.py
execute it after the container is up and configured.
Makes Containernet compatible to default containers like http:latest. Feature should be considered as experimental for now.
> Feature #101: Fetch CMD fields from image info and automatically

- examples/containernet_example_cmd_field.py
- mininet/node.py
Immediately starting the CMD field is nice for simple, standalone
containers. However, if the containers rely on a topology described by
containernet, their starting commands are likely going to fail because
the initialization of the network did not occur at the time at which the
command is executed.
Thus, giving the user the option to launch the processes at a
well-defined state of the network allows a lot more flexibility.
This change should also remove the need of workarounds like the
`VIM_EMU_CMD` handling in vim-emu.
Related to #105
> Do not automatically start CMD, but allow to run it after init

- mininet/link.py
`ifconfig` in general is deprecated in modern linux and apparently
busybox/alpine based distributions error when attempting to set an ip
address with a subnet:
$ ifconfig kafka-eth0 10.0.0.97/8
ifconfig: bad address '10.0.0.97/8'
I was unable to figure out why this happens, but it does not happen with
iproute2's ip command: `ip address add 10.0.0.97/8 dev kafka-eth0`
> Replace `ifconfig` with `ip` for setting ip address

- examples/example-containers/Dockerfile.centos7
On my system(s) **containernet_container_test.py** passed only when **iproute** is installed on CentOS 7 docker image.
> CentOS7 docker needs iproute installed

- mininet/node.py
get the shell when a command should be executed.
> Fix: Be a bit more relaxed and allow Containernet to wait up to 2s to

- mininet/node.py
This passes through a tmpfs argument to the `docker.create_config(...)` method, such that a tmpfs can be added.
> Add tmpfs support

- CONTRIBUTORS
- util/m
This allows us to run `util/m` for containers. The code checks if the node is a container or not.
> Enable mn for containers

- ansible/install.yml
- util/install.sh
This PR updates the following:
- Ansible from Containernet, uses updated naming on the packages
- `util/install.sh` from Mininet, uses updated naming on the packages as well as python3 versions of scrapy
Edit: currently, this passes all tests on `sudo make test` with 3 syntax warnings.
This closes #185 .
> Update ansible and util/install.sh for 20.04

- mininet/node.py
- mininet/test/test_containernet.py
Adds the `storage_opt` function from the docker API to Containernet.
Thereby it is e.g. possible to adjust the storage size of the Docker container.
E.g. this
```python
d0 = self.net.addDocker('d0', ip='10.0.0.1', dimage="ubuntu:trusty", storage_opt={'size': '42m'})
```
will result in a storage size of 42 Mb.
> Add storage_opt to Containernet

- mininet/node.py
- mininet/test/test_containernet.py
Reverts containernet/containernet#192
Seems like the extension creates a dependency to XFS. Reverting for now. Should be changed to be fully optional so that XFS in only required if option is used.
See: https://github.com/containernet/containernet/issues/193
> Revert "Add storage_opt to Containernet"

- mininet/node.py
This is a follow up on this PR (#192)  and  fixes the issue reported here #193. 
The main problem is that an empty dictionary leads to an initialization of the `storage_opt` in older versions of the docker server (e.g. 19.03.13), even if you don't specify any `storage_opt` in the `.addDocker()` function.
For example with docker server version 19.03.13:
```python
import docker
d = docker.APIClient()
config = d.create_host_config(storage_opt={})
c = d.create_container(host_config=config, image="ubuntu:trusty")
```
The last line will lead to the following error:
```sh
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 261, in _raise_for_status
response.raise_for_status()
File "/usr/lib/python3/dist-packages/requests/models.py", line …
```
> Fix storage_opt error with old docker versions

- mininet/node.py
- mininet/test/test_containernet.py
This adds back the `storage_opt` option to the `addDocker` function.
It refers to the original PR (#192) and a later fix of a bug (#196) which misses most of the original changes. 
Now all should be included and fine. Sorry for the inconvenience.
> Add storage_opt to Containernet again

- util/install.sh
I was having the error below until I updated the git clone command on `install.sh`
```
Cloning into 'openflow'...\nfatal: unable to connect to github.com:\ngithub.com[0: 140.82.121.3]: errno=Connection refused
```
> update git clone openflow in install.sh to prevent cloning error

- mininet/net.py
The check has to use the 'BaseString' from mininet.util, instead of 'basestring' to work with python3.
> fixed bug in configLinkStatus()

- examples/containernet_topology_example.py
- mininet/net.py
- mininet/topolib.py
This PR changes the default Containernet constructor to allow for topology objects together with a default image.
The Containernet class overrides the `buildFromTopo` method from Mininet. The `__init__` now calls the default Mininet constructor with `build=False`, so that we can still pass the topology object but not invoke the original `buildFromTopo`.
In `topolib`, the original `TreeNet` class returns a Mininet object. In order to keep the example consistent, the PR adds a `TreeContainerNet`, which also helps to test the class changes.
The PR includes an example similar to `examples/tree1024.py` from Mininet, under `examples/containernet_topology_example.py`.
This PR closes #207 .
> 207 topology support

- util/install.sh
- util/vm/install-mininet-vm.sh
In install.sh, there are two types of `git clone`
```
git clone https://[repo url]
git clone git://[repo url]
```
If we do not set public key on github, we cannot use git://[repo url].
When I used install.sh, `Permission denied (publickey)`  occurred.
So, I changed `git://` to `https://`
> Change protocol for connecting to github

- ansible/install.yml
- ansible/install_centos.yml
I noticed complications if you have `docker-ce` already installed and then ansible tries to  add the repo again.
The problems seem to occur if you  have multiple instances of the docker-repo installed with different gpg keys, or something like that.
Therefor, I thought it would be clever to test if it is installed, before doing anything.
> Add check if docker-ce is already installed

- mininet/net.py
- mininet/test/test_containernet.py
- mininet/topolib.py
This fixes an issue brought up by #212. We refactor how custom topologies are handled to avoid overriding core Mininet methods and make sure that the topology is responsible for declaring what type of host it requires. Previously the system did not call internal config methods of Mininet which prevented eg. the NAT from working in custom topologies.
> Refactor topology

- mininet/node.py
The current codebase will print out "1:" in all log modes.
> Removed an unnecessary print statement.

- .github/workflows/ci.yml
- Dockerfile.focal
This PR:
- Adds docker image for nested deployment based on Ubuntu 20.04
- Adds Ubuntu 20.04-based docker image to CI
- Rewrites current CI to use [GH action](https://github.com/docker/build-push-action) for building docker images
> Add Ubuntu 20.04-based Dockerfile for nested deployment
