containernet/containernet

.travis.yml

CI now tests containernet on trusty64 and xenial64!

Get a better CI integration

---

mininet/node.py

Sometimes the shell dies.
In this cases the next command will not be executed
and the last response from bash will be read from the process' stdout:
"exit".
Since the prompt does not return the thread hangs indefinitely.
This fix polls the shell process before each command and restarts the shell in case the process died.
This issue may be connected to https://github.com/mininet/mininet/issues/679

Fix shell dying

---

mininet/node.py

CLI does not detect the end of the executed command in a Docker host.
It seems to be related to the 'sentinel chr(127)' used in the mininet CLI to detect in the output if an executed cmd is finished. For Docker hosts this sentinel is now added explicitly.

fix for the CLI

---

mininet/clean.py
mininet/net.py
mininet/node.py

Due to a bug in iptc, we can only iterate through the iptables rules, we rely on iptables cli tool to add/remove iptables rules.
This fixes the docker build of son-emu.

cleanup the code that uses the iptc module

---

mininet/node.py

Fix cmdPrint() call via cmd() using docker-py API

---

util/docker/entrypoint.sh

Signed-off-by: Manuel Peuster <manuel@peuster.de>

Improved docker entrypoint script

---

mininet/node.py

Fix: Do not crash if images without tags are present on host machine.

---

.travis.yml

Optimized travis integration.

---

.travis.yml

Fix: env command does not work with latest TravisCI base images.

---

.travis.yml
CONTRIBUTORS
mininet/test/test_containernet.py
util/docker/Dockerfile
util/docker/Dockerfile.centos7

Also extended CI pipeline to run unittests within the
nested docker deployments.

Added CentOS integration done by @mrcdb to CI script.

---

.travis.yml
CONTRIBUTORS
Dockerfile.centos
ansible/install_centos.yml
examples/dockerhosts.py
mininet/node.py
mininet/test/test_containernet.py
util/docker/Dockerfile.centos7
util/docker/entrypoint_centos.sh
util/install.sh

Signed-off-by: peusterm <manuel@fgcn-of-1.cs.uni-paderborn.de>

Fix: Moved .travis changes from master to libvirt

---

.travis.yml
examples/containernet_container_test.py
examples/example-containers/Dockerfile.centos6
examples/example-containers/Dockerfile.centos7
examples/example-containers/Dockerfile.ubuntu1404
examples/example-containers/Dockerfile.ubuntu1604
examples/example-containers/Dockerfile.ubuntu1804
examples/example-containers/build.sh

(Temp. disabled broken centos CI tests.)

Added example containers that can be used in Containernet topologies.

---

.travis.yml

Fixing Travis CI

---

.travis.yml
util/docker/Dockerfile
util/docker/Dockerfile.centos7

CI optimizations

---

.travis.yml
ansible/install.yml
util/docker/Dockerfile
util/docker/Dockerfile.centos7

Improved output in installation. Added nopull tag.

---

setup.py
util/docker/Dockerfile
util/docker/Dockerfile.centos7

Fix: https://github.com/sonata-nfv/son-emu/issues/296

---

mininet/node.py

Redirect command output to docker logs

---

.travis.yml

Fix: Travis Python version now needs to be explicitly stated

---

ansible/install.yml

Fix: Install on 18.04 was broken

---

.gitignore
ansible/install.yml
ansible/install_centos.yml
ansible/install_vagrant.yml

Fix: Broken pytest dependency

---

CONTRIBUTORS
README.md
mininet/net.py
setup.py

Post-merge adaptions

---

mininet/node.py

Inc. grace time

---

examples/miniedit.py

this change in miniedit.py enables both python2 and python3 support

miniedit.py change to support python 2

---

mininet/node.py

Fix: Better handling of shell wait

---

ansible/install_centos.yml

Fix: CentOS installer was broken

---

.travis.yml

CI: Give Travis some more time

---

mininet/node.py

Feature: Allow cap_add options for individual containers.

---

examples/dockerhosts.py
mininet/node.py

Fix: Correctly check for existing container images. Solves a race

---

mininet/node.py

https://docker-py.readthedocs.io/en/2.0.2/containers.html - sysctls

 Feature: Allow sysctls options for individual containers

---

ansible/install.yml
ansible/install_centos.yml
ansible/install_vagrant.yml
mininet/node.py
mininet/test/test_containernet.py
setup.py

No changes except of implemented using image IDs for Docker on fly.

Docker py upgrade

---

.travis.yml

CI: Use Python 3.7

---

README.md

Signed-off-by: mpeuster <manuel@peuster.de>

Removed Gitter from README

---

ansible/install.yml
util/install.sh

Many thanks to Dimitrios (@digiou) for the patch.

Support for Ubuntu 20.04 LTS (experimental)

---

examples/miniedit.py

save and open didn't work with Mininet topologies. This was fixed.

fixed the issue with save/open

---

util/install.sh

This will fix #200
It updates the corresponding lines to the recent version from mininet/master to be compatible with ubuntu2010. It may be a good idea for the future to also update the rest with the recent changes from mininet.
I tested it on ubuntu2010 and ubuntu1804.

Change mininet installation to support ubuntu2010

---

mininet/node.py

As per our discussions in #208, I made the pull request. Let me know if there are any issues--from my testing, networking doesn't break so it should be good to go.

Don't run containers as privileged
